In [1]:
# SQL Alchemy
from sqlalchemy import create_engine

# PyMySQL 
import pymysql
pymysql.install_as_MySQLdb()

# Config variables
import config
from config import remote_db_endpoint, remote_db_port
from config import remote_db_name, remote_db_user, remote_db_pwd

# Import Pandas
import pandas as pd

## ETL

This code segment will migrate data from a local csv to your MySQL database hosted on AWS

In [3]:
# Cloud MySQL Database Connection on AWS
cloud_engine = create_engine(f"mysql://{remote_db_user}:{remote_db_pwd}@{remote_db_endpoint}:{remote_db_port}/{remote_db_name}")

# Create a remote database engine connection
cloud_conn = cloud_engine.connect()

In [4]:
fairfax_expenditures = pd.read_csv('../static/data/fairfax_expenditures.csv')
fairfax_expenditures.head()

    county  fiscal_year                         department expenditures_ytd
0  Fairfax         2013  ADMINISTRATION FOR HUMAN SERVICES   $11,569,374.71
1  Fairfax         2013          ALCOHOL AND DRUG SERVICES            $0.00
2  Fairfax         2013               BOARD OF SUPERVISORS    $4,554,678.86
3  Fairfax         2013      BUSINESS PLANNING AND SUPPORT      $739,969.50
4  Fairfax         2013        CABLE AND CONSUMER SERVICES    $1,712,730.11

In [5]:
fairfax_expenditures.to_sql(name='ncr_county_expenditures', if_exists='append', con=cloud_conn, index=False)

In [9]:
# read in from AWS to test
pd.read_sql("SELECT * FROM ncr_county_expenditures", cloud_conn)

,county,fiscal_year,department,expenditures_ytd
0,Fairfax,2013,ADMINISTRATION FOR HUMAN SERVICES,"$11,569,374.71"
1,Fairfax,2013,ALCOHOL AND DRUG SERVICES,$0.00
2,Fairfax,2013,BOARD OF SUPERVISORS,"$4,554,678.86"
3,Fairfax,2013,BUSINESS PLANNING AND SUPPORT,"$739,969.50"
4,Fairfax,2013,CABLE AND CONSUMER SERVICES,"$1,712,730.11"
...,...,...,...,...
450,Fairfax,2021,TAX ADMINISTRATION,"$13,590,873.37"
451,Fairfax,2021,TRANSPORTATION,"$3,735,409.29"
452,Fairfax,2021,UNCLASSIFIED ADMINISTRATIVE EXPENSES (NO,"$26,452,092.17"
453,Fairfax,2021,UNCLASSIFIED ADMINISTRATIVE EXPENSES (PU,"$303,598.00"
454,Fairfax,2021,WASTEWATER,$66.12